# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: HTML Proofer
    env:
      HTMLPROOFER_OPTIONS: './_site --internal-domains=pid.codes --check-html --check-opengraph --report-missing-names --log-level=:debug --url-ignore /www.andreas.org/,/www.kbles.ru/,/github.com\/KK2345\/TinyPassword$/,/github.com\/KK2345\/TinyPassword\/blob\/master\/README.md/,/www.oshec.org/,/github.com\/xuio\/Cynteract$/,/github.com\/mattomatto\/craft$/,/triparts.strikingly.com$/,/facebook.com/varioskybean$/'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python3 -m test.validate_pids
